import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div id="nav" className='flex items-center justify-between m-2 p-4'>
        <a href='/' id="logo" className='w-80'><img src='./logo.png' /></a>
        <a href="#" id="menu__item"> News </a>
        <a href="#" id="menu__item"> About Us </a>
        <a href="#" id="menu__item"> Contact Us </a>
      </div>

      {/* Top */}
      <div id="top" className='md:flex lg:flex'>
        <div id='left' className='bg-yellow-500 w-full md:w-1/2 lg:w-1/2 flex md:pt-28 lg:pt-28'>
          {/* Filler */}
          <div className='hidden md:block lg:block md:w-1/4 lg:w-1/4'></div>
          <img src='./banner.jpg' className='w-full md:w-3/4 lg:w-3/4' />
        </div>

        <div id='right' className='bg-yellow-100 w-full lg:w-1/2 md:w-1/2 md:pt-28 lg:pt-28'>
          {/* Content */}
          <div className='w-full md:w-3/4 lg:w-3/4 p-2 space-y-6 text-green-900'>
            {/* Heading */}
            <p className='font-bold text-4xl md:text-7xl lg:text-7xl'>A Safer World; <br />
           One Neighbourhood at a time.</p>

           {/* Explainer */}
           <p>
           Our objective is to offer a secure neighborhood for families, as well as basic human comforts and security for everyone, particularly the most vulnerable.
           </p>

           {/* CTA */}
          <button href='#' className='main__btn'>
             Donate Now
          </button>

          <button href='#' className='alt__btn'>
             About Us
          </button>
          <br />
        </div>
          {/* Filler */}
          <div className='hidden md:block lg:block md:w-1/4 lg:w-1/4'></div>
        </div>
      </div>
    </div>
  )
}
